name: Test
on:
  pull_request_target

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug
      - run: echo ${{ github.head_ref }}.${{ github.sha }}